name: Restrict PRs to Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Base Branch
        if: github.event.pull_request.head.ref != 'workingbranch'
        run: |
          echo "PR can only be created from 'workingbranch' to 'main'."
          exit 1
